config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :welcome, only: [:index]
  resources :users

  resources :parks, only: [:index, :show, :destroy, :new]
  resources :reviews, only: [:destroy]

  namespace :api do
    namespace :v1 do
      resources :parks, only: [:show, :create, :index] do
        resources :users, only: [:show] do
          resources :follows, only: [:index]
        end
        resources :reviews, only: [:index]
	      resources :users, only: [:show] do
	       resources :follows, only: [:index]
	      end
      end
      resources :reviews, only: [:show] do
        resources :users, only: [:show] do
          resources :votes, only: [:index]
        end
      end
      resources :votes, only: [:create]
      resources :reviews, only: [:create]
      resources :follows, only: [:create]
    end
  end
end

app/models/park.rb
class Park < ApplicationRecord
  validates :name, presence: true
  validates :state, presence: true
  validates :link_url, presence: true
  validates :avg_rating,
    numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 },
    allow_nil: true
  validates :dog_friendly_avg_rating,
    numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 },
    allow_nil: true
  validates :camping_avg_rating,
    numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 },
    allow_nil: true
  validates :playground_avg_rating,
    numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 },
    allow_nil: true
  validates :hiking_avg_rating,
    numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 },
    allow_nil: true
  validates :scenery_avg_rating,
    numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 },
    allow_nil: true

  def self.search_name(park)
    if park
      where('name LIKE ?', "%#{park}%")
    else
      @parks = []
    end
  end

  def self.search_state(park)
    if park
      where('state LIKE ?', "%#{park}%")
    else
      @state = []
    end
  end

  def self.search_dog(park)
    if park
      where('dog_friendly_avg_rating LIKE ?', "%#{park}%")
    else
      @dog = ''
    end
  end

  has_many :reviews
  has_many :follows
  has_many :users, through: :follows
end

app/controllers/api/v1/parks_controller.rb
class Api::V1::ParksController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    render json: Park.all
  end

  def show
    park = Park.find(params[:id])
    render json: {park: park}
  end

  def create
    data = JSON.parse(request.body.read)
    park = Park.new(data)
    park.save
    if park.id
      render json: {id: park.id}
    end
  end
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController

  def index

    @result_parks = []
    @parks = []
    if (params[:park] != '')
      @parks = Park.search_name(params[:park])
      @result_parks = (@result_parks + @parks).uniq
    else
      @parks = []
    end


    if (params[:state] != '')
      @state = Park.search_state(params[:state])
      @result_parks = (@result_parks + @state).uniq
    else
      @state = []
    end

    if (params[:dog_friendly_avg_rating])
      @result_parks.delete_if { |p| p.dog_friendly_avg_rating.nil? }
    end

    if (params[:camping_avg_rating])
      @result_parks.delete_if { |p| p.camping_avg_rating.nil? }
    end

    if (params[:playground_avg_rating])
      @result_parks.delete_if { |p| p.playground_avg_rating.nil? }
    end

    if (params[:hiking_avg_rating])
      @result_parks.delete_if { |p| p.hiking_avg_rating.nil? }
    end

    if (params[:scenery_avg_rating])
      @result_parks.delete_if { |p| p.scenery_avg_rating.nil? }
    end

  end

  before_action :authorize_user, only: [:destroy]

  def show
    @id = params[:id]
    @park = Park.find(params[:id])

  end

  def new
    @id = params[:id]
  end

  def destroy
    @park = Park.find(params[:id])
    @park.destroy
    redirect_to users_path, notice: 'Park was successfully destroyed.'
  end

  private
  def authorize_user
    if !user_signed_in? || !current_user.admin?
      raise ActionController::RoutingError.new("Not Found")
    end
  end
end

app/views/parks/index.html.erb
<div class="row">
  <div class="panel">



  <h1 align="center">Search for a Park</h1>

    <div class="park-search">

      <%= form_tag(parks_path, method: :get) do %>

        <%= label :park, "Park Name" %><br />
        <%= text_field_tag :park, nil %>

      <%= form_tag(parks_path, method: :get) do %>
        <%= label :state, "State" %><br />
        <%= text_field_tag :state, nil %>

        <%= submit_tag 'Search' %><br>

        <div align="center">
          <h4> Filter by</h4>
          <%= check_box_tag(:dog_friendly_avg_rating) %>
          <%= label_tag(:dog_friendly_avg_rating, "Good for Dogs") %>

          <%= check_box_tag(:camping_avg_rating) %>
          <%= label_tag(:camping_avg_rating, "Good for Camping") %>

          <%= check_box_tag(:playground_avg_rating) %>
          <%= label_tag(:playground_avg_rating, "Good Playgrounds") %>

          <%= check_box_tag(:hiking_avg_rating) %>
          <%= label_tag(:hiking_avg_rating, "Good for Hiking") %><br>
        </div>
      <% end %>
    <% end %>
    </div>
    <br><br>

    <div class="serch-result">
     <% if @result_parks.length != 0 %>
       <h5 align="center">Click On a Park For More Information</h5>
         <% @result_parks.each do |p| %>
          <div class="panel">
            <h4><%=link_to p.name, park_path(p) %></h4>
            <h6><%= p.state %></h6>
            <div>
              <strong>Overall Park Rating: <%= p.avg_rating %></strong><br>
              Dog friendly: <%= p.dog_friendly_avg_rating %><br>
              Camping: <%= p.camping_avg_rating %><br>
              Playgrounds: <%= p.playground_avg_rating %><br>
              Scenery: <%= p.scenery_avg_rating %><br>
              Hiking: <%= p.hiking_avg_rating %>
            </div>
          </div>
        <% end %>
    <% end %>
    </div>
  </div>
</div>

app/views/parks/new.html.erb
<div class="row">
 <div class="panel">



    <h1 align="center">Add a Park:</h1>


    <div id="form" >

    </div>

 </div>
</div>

app/views/parks/show.html.erb
<div class="row">
  <div class="panel">
    <h2 align="center"><%= @park.name %></h2><br>
    <h4 align="center"><%= @park.state %></h4><br>
    <% if @park.description %>
    <h4>Description: <%= @park.description %> </h4>
    <% end  %>
    <p><%= link_to "Go to park website", "http://#{@park.link_url}" %></p>
    <div id="app" data-park_id= <%= @id %> data-user_id= <%= current_user && current_user.id %> ></div>
  </div>
</div>