config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :welcome, only: [:index]
  resources :users

  resources :parks, only: [:index, :show, :destroy, :new]
  resources :reviews, only: [:destroy]

  namespace :api do
    namespace :v1 do
      resources :parks, only: [:show, :create, :index] do
        resources :users, only: [:show] do
          resources :follows, only: [:index]
        end
        resources :reviews, only: [:index]
	      resources :users, only: [:show] do
	       resources :follows, only: [:index]
	      end
      end
      resources :reviews, only: [:show] do
        resources :users, only: [:show] do
          resources :votes, only: [:index]
        end
      end
      resources :votes, only: [:create]
      resources :reviews, only: [:create]
      resources :follows, only: [:create]
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Park Planner" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Rubik+Mono+One" rel="stylesheet">
  </head>

  <body>
    <div class="top-bar">
        <% if user_signed_in?  %>
          <ul class="menu">
            <div class="left">
              <li class="button"><%= link_to 'Add A Park', new_park_path %></li>
              <li class="button"><%= link_to "Back", :back %></li>
              <li class="button"><%= link_to "Search", parks_path %></li>
            </div>
            <div class="right">
              <% if current_user.admin? %>
                <li class="button"><%= link_to 'Admin', users_path %></li>
              <% end %>
              <li class="button"><%= link_to 'My Account', user_path(current_user) %></li>
              <li class="button"><%= link_to 'Edit Account Info', edit_user_registration_path %></li>
              <li class="button"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
            </div>
          </ul>
        <% else %>
          <ul>
            <div class="left">
              <li class="button"><%= link_to "Sign In", new_user_session_path %></li>
              <li class="button"><%= link_to "Sign Up", new_user_registration_path %></li>
            </div>
          </ul>
        <% end %>
      </div>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>